name: mindmaple
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI関連
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  table_calendar: ^3.0.9

  # 状態管理
  provider: ^6.0.5

  # グラフ描画
  fl_chart: ^0.63.0  # グラフ表示のために使用

  # プッシュ通知
  onesignal_flutter: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/calendar_icon.svg
    - assets/images/graph_icon.svg
    - assets/images/task_create_icon.svg
    - assets/images/mindmaple_logo.png
    - assets/images/google_logo.png
    - assets/images/header_logo.svg
    - assets/images/home_icon.svg
    - assets/images/save_icon.svg
    - assets/images/back_icon.svg
    - assets/images/delete_icon.svg
